repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
    - id: check-added-large-files
    - id: trailing-whitespace
    - id: detect-private-key
    - id: mixed-line-ending
    - id: requirements-txt-fixer
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.24.0
    hooks:
    - id: yapf
