baseURL = "https://alex.guinman.id.au/"
languageCode = "en-gb"
title = "Alex's Blog"
subtitle = "Personal blog of Alex Guinman"
theme = "ananke"
paginate = 6

[params]
  favicon = ""
  description = "Personal blog of Alex Guinman"
  featured_image = "posts/2018/upper-gorge/creek1.jpg"

  # Social Links
  #parkrun = "http://www.parkrun.com.au/results/athleteresultshistory/?athleteNumber=1694205"
  #goodreads = "http://www.goodreads.com/aguin"
  #strava = "https://www.strava.com/athletes/aguinane"
  #youtube = "https://www.youtube.com/user/aguin01"
  #github = "https://github.com/aguinane"
  #linkedin = "https://www.linkedin.com/in/alexguinane"
  #wikitree = "https://www.wikitree.com/treewidget/Guinane-16/5"


[permalinks]
  posts = "posts/:year/:slug/"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  
[[menu.main]]
    name = "Travel"
    pre = "<i class='fa fa-folder-open'></i>"
    weight = 1
    identifier = "travel"
    url = "/categories/travel/"

[[menu.main]]
    name = "Music"
    pre = "<i class='fa fa-folder-open'></i>"
    weight = 2
    identifier = "music"
    url = "/categories/music/"

[[menu.main]]
    name = "Misc"
    pre = "<i class='fa fa-folder-open'></i>"
    weight = 3
    identifier = "misc"
    url = "/categories/misc/"

[[menu.main]]
    name = "About"
    pre = "<i class='fa fa-info-circle'></i>"
    weight = 4
    identifier = "about"
    url = "/pages/about"

[[menu.main]]
    name = "1SE"
    pre = "<i class='fa fa-info-circle'></i>"
    weight = 5
    identifier = "1se"
    url = "/pages/1se"



