baseURL = "https://alex.guinman.id.au/"
languageCode = "en-gb"
title = "Alex's Blog"
subtitle = "Personal blog of Alex Guinman"
theme = "ananke"
paginate = 9

[params]
  favicon = ""
  description = "Personal blog of Alex Guinman"
  featured_image = "posts/2018/upper-gorge/creek1.jpg"

[permalinks]
  posts = "posts/:year/:slug/"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  
[[menu.main]]
    name = "Travel"
    pre = "<i class='fa fa-folder-open'></i>"
    weight = 1
    identifier = "travel"
    url = "/categories/travel/"

[[menu.main]]
    name = "Misc"
    pre = "<i class='fa fa-folder-open'></i>"
    weight = 3
    identifier = "misc"
    url = "/categories/misc/"

[[menu.main]]
    name = "About"
    pre = "<i class='fa fa-info-circle'></i>"
    weight = 4
    identifier = "about"
    url = "/pages/about"

[[menu.main]]
    name = "1SE"
    pre = "<i class='fa fa-info-circle'></i>"
    weight = 5
    identifier = "1se"
    url = "/pages/1se"



