baseURL = "https://alex.guinman.id.au/"
languageCode = "en-gb"
title = "Alex Guinman"
subtitle = "Personal blog of Alex Guinman"
theme = "alex"
paginate = 9
googleAnalytics = "UA-163360018-1"

[outputs]
  home = ["HTML", "RSS"]

[markup.goldmark.renderer]
  unsafe= true

[params]
  author = "Alex Guinman"
  description = "Personal blog of Alex Guinman"
  favicon = ""
  themeColor = "theme-base-08"
  layoutReverse = true
  relatedPosts = true

[permalinks]
  posts = "posts/:year/:slug/"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[menu.main]]
    name = "Travel"
    identifier = "travel"
    url = "/categories/travel/"

[[menu.main]]
    name = "Misc"
    identifier = "misc"
    url = "/categories/misc/"
