baseURL = "https://alex.guinman.id.au/"
languageCode = "en-gb"
title = "Alex's Blog"
subtitle = "Personal blog of Alex Guinman"
theme = "alex"
paginate = 9

[outputs]
  home = ["HTML", "RSS"]

[params]
  favicon = ""
  description = "Personal blog of Alex Guinman"
  featured_image = "posts/2018/upper-gorge/creek1.jpg"
  themeColor = "theme-base-08"
  layoutReverse = true
  relatedPosts = true

[permalinks]
  posts = "posts/:year/:slug/"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[menu.main]]
    name = "Travel"
    identifier = "travel"
    url = "/categories/travel/"

[[menu.main]]
    name = "Misc"
    identifier = "misc"
    url = "/categories/misc/"

[[menu.main]]
    name = "About"
    identifier = "about"
    url = "/pages/about"

[[menu.main]]
    name = "1SE"
    identifier = "1se"
    url = "/pages/1se"
